name: Semver Tagging

on:
  push:
    tags:
      - v*

env:
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  tag-main-with-semver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker login
        run: |
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin "${DOCKER_REGISTRY}"

      - name: Docker pull
        run: |
          docker pull ${DOCKER_REGISTRY}/navigator-backend:main-${GITHUB_SHA::8}
          docker pull ${DOCKER_REGISTRY}/navigator-frontend:main-${GITHUB_SHA::8}

      - name: Docker retag locally
        run: |
          docker tag ${DOCKER_REGISTRY}/navigator-backend:main-${GITHUB_SHA::8}  navigator-backend:main-${GITHUB_SHA::8} 
          docker tag ${DOCKER_REGISTRY}/navigator-frontend:main-${GITHUB_SHA::8}  navigator-frontend:main-${GITHUB_SHA::8} 

      - name: Docker push
        run: |
          .github/retag-and-push.sh navigator-backend main-${GITHUB_SHA::8}
          .github/retag-and-push.sh navigator-frontend main-${GITHUB_SHA::8}
